#!/usr/bin/bash
has() {
	type -t "$1" &>/dev/null
}

if [[ -n $BROWSER ]]; then
	exec "$BROWSER" "$@"
elif has gio; then
	browser=$(gio mime text/html | sed -n '1s/.*: //p')
	applications=(
		"${XDG_DATA_HOME:-$HOME/.local/share}/applications"
		/usr/local/share/applications
		/usr/share/applications
	)
	for d in "${applications[@]}"; do
		entry="$d/$browser"
		[[ -f $entry ]] && exec gio launch "$entry" "$@" 1>/dev/null 2>/dev/null
	done
else
	for b in chromium firefox google-chrome-stable; do
		if has "$b"; then
			exec "$b" "$@"
		fi
	done
fi
